### ISSUE TITLE
investigate python 3.7 bug

### ISSUE THREAD

**Issue by jimboid** [HECBioSim/Longbow#129]
During workshop. The activity submitting many different types of jobs. A user showed an error message that looked like Longbow could not parse namd command-lines under python 3.7. Check if there is a unit test that would see this, if there is not then this is potentially a bug and should be fixed along with new unit tests to verify future versions.

**Comment by drewsilcock** [comment]
Just testing this out now on branch - takes a while to get to the point where it fails so I'll let you know what happens 🙂

**Comment by drewsilcock** [comment]
Looks like the issue isn't appearing anymore on that branch 👍 Thanks for the quick fix!

**Comment by jimboid** [comment]
Excellent, I'll merge to master. I'm hoping to get 1.5.3 out by the end of the week so you'll be able to install via pypi again.
