### ISSUE TITLE
Sandbox error when installing Longbow from setup.py.

### ISSUE THREAD

**Issue by drewsilcock** [HECBioSim/Longbow#130]
## Reproduction Steps

When running `python setup.py install` on a `setup.py` script that includes "longbow" in its list of `install_requires`, I am getting the following error:

```sh
$ python setup.py install
>>> Searching for Longbow
>>> Reading https://pypi.python.org/simple/Longbow/
>>> Downloading https://files.pythonhosted.org/packages/c5/76/32f5562d161ab62fe549488ca144d288ffda47ebb6b127fb3ca891c0aaf5/Longbow-1.5.2.tar.gz#sha256=20817372ef4204534737e42726dbb627be610abe11245750469b683b6f1be195
>>> Best match: Longbow 1.5.2
>>> Processing Longbow-1.5.2.tar.gz
>>> Writing /var/folders/cs/x2yk4h5n409ghnhmgt22ljf40000gq/T/easy_install-coyiirs9/Longbow-1.5.2/setup.cfg
>>> Running Longbow-1.5.2/setup.py -q bdist_egg --dist-dir /var/folders/cs/x2yk4h5n409ghnhmgt22ljf40000gq/T/easy_install-coyiirs9/Longbow-1.5.2/egg-dist-tmp-0qgl7oa3
>>> The Python version installed "3.6" is supported by Longbow.
>>> zip_safe flag not set; analyzing archive contents...
>>> longbow.__pycache__.entrypoints.cpython-36: module references __file__
>>> longbow.apps.__pycache__.__init__.cpython-36: module references __file__
>>> longbow.schedulers.__pycache__.__init__.cpython-36: module references __file__
>>> Since version 1.5.0 '~/.Longbow' directory has been all lowercase, moving '~/.Longbow' to '~/.longbow'.
>>> error: SandboxViolation: rename('/Users/drew/.Longbow', '/Users/drew/.longbow') {}
>>> 
>>> The package setup script has attempted to modify files on your system
>>> that are not within the EasyInstall build area, and has been aborted.
>>> 
>>> This package cannot be safely installed by EasyInstall, and may not
>>> support alternate installation locations even if you run its setup
>>> script by hand.  Please inform the package's author and the EasyInstall
>>> maintainers to find out if a fix or workaround is available.
```

## Workaround:

```
$ pip install longbow
$ python setup.py install
```

As Longbow is already installed here it's not installed as part of the `setup.py` and so it doesn't seem to be restricted to the EasyInstall sandbox.

## Additional Information

```sh
$ python --version
>>> Python 3.6

$ pip --version
>>> pip 10.0.1 from /Users/drew/.../.env-3.6/lib/python3.6/site-packages/pip (python 3.6)
```

**Comment by jimboid** [comment]
Thanks for reporting that. It looks like that is tripped by moving files outside of your sandbox. That is actually legacy code that renames the configuration directory from older versions of Longbow upon update or fresh install. 

We could delete that code now. But we would still need to create new directories on fresh install, I'm guessing this would still trip this error upon install though.

**Comment by jimboid** [comment]
Is the application calling Longbow creating a directory called ".Longbow"? what happens if you modify this so it creates one called ".longbow"? Do any of the other lines in the setup trigger the sandbox error? I'm guessing Valeria started this project with an old Longbow version.

**Comment by drewsilcock** [comment]
The application I'm working on doesn't use the `~/.longbow` folder at all in fact, it just creates a hosts file in the active directly which Longbow uses over the`~/.longbow/hosts.conf`. The `setup.py` doesn't list the specific version of Longbow (I've got pinned versions in the `requirements.txt`).

**Comment by jimboid** [comment]
In that case it makes it even weirder that it is triggering this operation in the setup.py:

`Since version 1.5.0 '~/.Longbow' directory has been all lowercase, moving '~/.Longbow' to '~/.longbow'.`

That should only happen if the directory ".Longbow" is present in your user home. So in your case is this being triggered without that directory existing? I was wondering if there was an old directory from Valeria lurking in the files somewhere because she would have used these old versions of Longbow in the past.

It is a temporary piece of code to allow users with old versions of longbow to do the pip update to the latest versions from really old versions.

**Comment by drewsilcock** [comment]
I'm on macOS, so the OS imposes a case-independence on top of the filesystem. I have a `~/.longbow` folder but no `~/.Longbow` folder, however if do `file ~/.Longbow` it will happily tell you that it exists.

**Comment by jimboid** [comment]
Hi Drew,

I think that I might have a solution to this. I've just implemented a --no-home-cfg flag that is an argument to setup.py which disables the creation of the ~/.longbow directory and the files underneath it. This is strictly only useful for folks like yourself that are using longbow like an API.

You can trigger this by either doing:

python setup.py --no-hosts-cfg install --user

or in a requirements.txt

longbow >= 1.5.3 --install-option="--no-home-cfg"

It doesn't however work with normal 'pip install longbow --user', not sure why though, you'll have to wait for the 1.5.3 version to hit pip to test it in a requirements.txt I think.
