### ISSUE TITLE
Longbow doesn't support NAMD SMP builds

### ISSUE THREAD

**Issue by jimboid** [HECBioSim/Longbow#66]
The crux of supporting this is that the namd2 executable needs various extra parameters to get the threads allocated correctly.

Non-SMP runs look like this:

aprun -n 24 -N 24 namd2 inputfile > outputfile

SMP runs look something like this:

aprun -n 24 -N 24 namd2 +ppn 23 inputfile > outputfile

At worst it might have to be:

aprun -n 24 -N 24 namd2 +ppn 23 +pemap 1-23 +commap 0 inputfile > outputfile

We could look at trying to support auto populating these as we do the parameters to aprun, but this would be quite complex. It is probably best to simply have the user give these themselves so that they can tweak the ratio +pemap:+commap for themselves. This would mean Longbow simply has to understand the +xxxx commandline parameters are not files and simply relay them onto the job submit file.

**Comment by jimboid** [comment]
So after having a quick play around with NAMD the following info is useful here.

aprun -n 1 -N 1 namd2 +ppn 23 +pemap 1-23 +commap 0 bench.in > bench.log 
1 node, 1 MPI proc per node, 23 worker threads per node, 1 comm thread

aprun -n 2 -N 1 namd2 +ppn 23 +pemap 1-23 +commap 0 bench.in > bench.log
2 nodes, 1 MPI proc per node, 23 worker threads per node, 1 comm thread

aprun -n 2 -N 1 -d 48 -j 2 namd2 +ppn 47 +pemap 1-47 +commap 0 bench.in > bench.log
2 nodes, 1 MPI proc per node, hyperthreaded cores, 47 worker threads per node, 1 comm thread

-n is number of total MPI processes
-N is the number of MPI processes per node
+ppn is the number of worker threads
+pemap is the worker thread mapping
+commap is the communication thread mapping

**Comment by CharlieLaughton** [comment]
In the spirit of keeping Longbow easy to use for relative newbies (to HPC), I think it would be nice if both options were supported - i.e. if the user does not supply '+' options then Longbow supplies some default ones.

**Comment by jimboid** [comment]
Yes, I think you are right, there has been a lot of confusion from new users to NAMD when ARCHER switched the default module from NAMD 2.9 (built without SMP) to 2.12 (defaulted to SMP). I'm not sure why as yet, this did cause so many users to ask for support since the non-SMP version of 2.12 could simply be loaded rather than opting for the default. I'm also not sure if this change by ARCHER reflects their plans to move to SMP only builds in future (possibly will be the case for ARCHER2 if they are going for accelerators).

From the playing around I did it should be as simple as providing three new parameters, say "namd-ppn", "namd-pemap" and "namd-commmap" which users can either override manually if they want undersubscription or if they want more comm threads etc. Otherwise Longbow ought to be able to use the number of cores and the cores per node to calculate all of those parameters.
