### ISSUE TITLE
Specifying a Generic Resource Scheduling (GRES) flag for SLURM

### ISSUE THREAD

**Issue by jjuarez84** [HECBioSim/Longbow#76]
Hi James,

Is it possible to specify a gres flag for the SLURM scheduler? To work with our cluster it would be very useful that the batch script generated by longbow would contain a line similar to

#SBATCH --gres=gpu:1 

I have attempted using the script parameter as a workaround, but with no success. This is the relevant part of the output  I get when the configuration file includes this line
**scripts = #SBATCH --gres=gpu:1**
or this one
**scripts = "#SBATCH --gres=gpu:1"**

2017-10-31 18:09:03 - Initialisation complete.
2017-10-31 18:09:03 - Loading configuration information from file 'mypath/hosts.conf'
2017-10-31 18:09:03 - too many values to unpack (expected 2)

Many thanks

**Comment by jimboid** [comment]
Hi Jordi,

Yes I can add support for this flag into Longbow. I'll place this under the next release (due shortly). I'll comment back here once I have implementation details.

**Comment by jimboid** [comment]
I have just added support for this, it is currently on the "release-prep" branch so will form part of version 1.5.1. Basically I added support so that in your host or job configuration file, you can add slurm-gres = gpu:1 and it will add that line into your job submit file.

**Comment by jimboid** [comment]
Closing as solution added
